<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Category;
use App\Models\Collection;
use App\Models\Brand;
use App\Models\FragranceFamily;
use App\Models\Product;
use App\Models\ProductVariant;
use App\Models\ActivityLog;

class ImagePerfumesInventorySeeder extends Seeder
{
    public function run()
    {
        // 1. Ensure Brand
        $brand = Brand::firstOrCreate(
            ['slug' => 'ravaha-signature-ateliers'],
            [
                'name' => 'RAVAHA Signature Ateliers',
                'origin_country' => 'Paris / Lahore Atelier',
                'is_featured' => true,
                'is_active' => true,
            ]
        );

        // 2. Ensure Categories
        $catExclusive = Category::firstOrCreate(
            ['slug' => 'exclusive-reserve'],
            [
                'name' => 'Exclusive Reserve',
                'description' => 'Our ultra-niche private reserve crafted with rare absolutes and exclusive macerations.',
                'image' => 'assets/images/categories/collection_signature.jpg',
                'badge_text' => 'Private Reserve',
                'sort_order' => 7,
                'is_active' => true,
            ]
        );

        $catOud = Category::where('slug', 'royal-oud-extrait')->first();
        $catFrench = Category::where('slug', 'french-niche-collection')->first();
        $catAttar = Category::where('slug', 'attar')->orWhere('slug', 'pure-attar-oils')->first();
        $catFloral = Category::where('slug', 'imperial-floral-saffron')->first();

        // 3. Ensure Collections
        $colExclusive = Collection::where('slug', 'exclusive')->first();
        $colMen = Collection::where('slug', 'men')->first();
        $colWomen = Collection::where('slug', 'women')->first();
        $colUnisex = Collection::where('slug', 'unisex')->first();

        // 4. Fragrance Families
        $ffWoody = FragranceFamily::where('slug', 'woody-oriental-oud')->first();
        $ffFloral = FragranceFamily::where('slug', 'floral-amber')->first();
        $ffLeather = FragranceFamily::where('slug', 'smoky-leather-spice')->first();
        $ffFresh = FragranceFamily::where('slug', 'citrus-aromatic-mist')->first();
        $ffGourmand = FragranceFamily::where('slug', 'gourmand-bourbon-vanilla')->first();

        // 5. 26 Perfumes from User Note Image
        $perfumes = [
            [
                'name' => 'Lattafa Khumrah',
                'impression_of' => 'Midnight Oud Exclusive (Lattafa Khamrah Impression)',
                'slug' => 'lattafa-khumrah-midnight-oud-exclusive',
                'sku' => 'PC-LAT-KHUMRAH',
                'category_id' => $catExclusive ? $catExclusive->id : $catOud->id,
                'fragrance_family_id' => $ffGourmand ? $ffGourmand->id : 5,
                'gender' => 'Unisex',
                'price' => 3850.00,
                'sale_price' => 3450.00,
                'compare_at_price' => 4500.00,
                'stock' => 50,
                'volume_ml' => 50,
                'collections' => array_filter([$colExclusive?->id, $colUnisex?->id]),
                'tagline' => 'Warm Resinous Dates, Sweet Cinnamon, Praline & Midnight Smoked Oud',
                'description' => 'An opulent, sensual gourmand oriental elixir. Opens with a decadent swirl of rich spiced dates, fiery cinnamon, and nutmeg, melting into a heart of velvety praline and tuberose, anchored by smoked benzoin, bourbon vanilla, and precious midnight agarwood.',
                'top_notes_summary' => 'Cinnamon, Nutmeg, Calabrian Bergamot',
                'heart_notes_summary' => 'Spiced Dates, Praline, Tuberose, Mahonial',
                'base_notes_summary' => 'Bourbon Vanilla, Tonka Bean, Benzoin, Smoked Agarwood, Amberwood',
                'thumbnail_image' => 'assets/images/perfumes/oud_royale.svg',
                'hover_image' => 'assets/images/perfumes/oud_royale_box.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => true,
            ],
            [
                'name' => 'Eclair (Caramel Fantasy)',
                'impression_of' => 'Caramel Fantasy Exclusive (Lattafa Eclaire Impression)',
                'slug' => 'eclair-caramel-fantasy-exclusive',
                'sku' => 'PC-ECL-CARAMEL',
                'category_id' => $catExclusive ? $catExclusive->id : $catFrench->id,
                'fragrance_family_id' => $ffGourmand ? $ffGourmand->id : 5,
                'gender' => 'Women',
                'price' => 3850.00,
                'sale_price' => 3400.00,
                'compare_at_price' => 4600.00,
                'stock' => 45,
                'volume_ml' => 50,
                'collections' => array_filter([$colExclusive?->id, $colWomen?->id, $colUnisex?->id]),
                'tagline' => 'Decadent Golden Caramel, Sweet Milk, Whipped Cream & Honeyed Vanilla',
                'description' => 'A luscious indulgence of milky caramel confection and whipped sugar. Evoking artisanal French patisseries, this cozy gourmand wraps you in a comforting aura of melted butterscotch, white blossoms, and silky Madagascar vanilla.',
                'top_notes_summary' => 'Caramel, Sweet Condensed Milk, Wild Honey',
                'heart_notes_summary' => 'Whipped Cream, White Flowers, Roasted Almonds',
                'base_notes_summary' => 'Madagascar Vanilla Bean, Praline, Soft White Musk',
                'thumbnail_image' => 'assets/images/perfumes/gourmand_tonka.svg',
                'hover_image' => 'assets/images/perfumes/gourmand_tonka.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => true,
            ],
            [
                'name' => 'Marjaan',
                'impression_of' => 'Marjaan Unisex Extrait',
                'slug' => 'marjaan-unisex',
                'sku' => 'PC-MRJ-UNISEX',
                'category_id' => $catAttar ? $catAttar->id : $catOud->id,
                'fragrance_family_id' => $ffFloral ? $ffFloral->id : 2,
                'gender' => 'Unisex',
                'price' => 3500.00,
                'sale_price' => 2999.00,
                'compare_at_price' => 4200.00,
                'stock' => 35,
                'volume_ml' => 50,
                'collections' => array_filter([$colUnisex?->id]),
                'tagline' => 'Precious Red Amber, Saffron Threads & Radiant Damascena Rose',
                'description' => 'Marjaan is an enchanting bridge between traditional oriental warmth and modern floral luxury. Bursting with crisp ruby apple and golden saffron over a velvety bed of dark amber and sacred woods.',
                'top_notes_summary' => 'Red Apple, Kashmiri Saffron, Pink Pepper',
                'heart_notes_summary' => 'Damascena Rose Petals, Lahori Jasmine, Patchouli',
                'base_notes_summary' => 'Warm Ambergris, Mysore Sandalwood, Royal White Musk',
                'thumbnail_image' => 'assets/images/perfumes/kashmir_saffron.svg',
                'hover_image' => 'assets/images/perfumes/kashmir_saffron.svg',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new_arrival' => true,
            ],
            [
                'name' => 'My Way (Paris Ladies)',
                'impression_of' => 'Paris Ladies (Armani My Way Impression)',
                'slug' => 'my-way-paris-ladies',
                'sku' => 'PC-MYW-PARIS',
                'category_id' => $catFloral ? $catFloral->id : $catFrench->id,
                'fragrance_family_id' => $ffFloral ? $ffFloral->id : 2,
                'gender' => 'Women',
                'price' => 3500.00,
                'sale_price' => 2999.00,
                'compare_at_price' => 4200.00,
                'stock' => 40,
                'volume_ml' => 50,
                'collections' => array_filter([$colWomen?->id]),
                'tagline' => 'Radiant Egyptian Orange Blossom, Indian Tuberose & Silky Vanilla',
                'description' => 'An authentic impression of the iconic Paris floral masterpiece. A bright and luminous white bouquet crafted with vibrant citrus blossoms, intoxicating night-blooming tuberose, and an elegant base of cedarwood and bourbon vanilla.',
                'top_notes_summary' => 'Egyptian Orange Blossom, Calabrian Bergamot',
                'heart_notes_summary' => 'Indian Tuberose, Jasmine Sambac',
                'base_notes_summary' => 'Madagascar Vanilla, Virginian Cedarwood, White Musk',
                'thumbnail_image' => 'assets/images/perfumes/jasmine_royale.svg',
                'hover_image' => 'assets/images/perfumes/jasmine_royale.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Afnan Supremacy',
                'impression_of' => 'Supremacy Silver Pour Homme (Afnan Supremacy Impression)',
                'slug' => 'afnan-supremacy',
                'sku' => 'PC-AFN-SUPREMACY',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffLeather ? $ffLeather->id : 3,
                'gender' => 'Men',
                'price' => 3950.00,
                'sale_price' => 3499.00,
                'compare_at_price' => 4800.00,
                'stock' => 40,
                'volume_ml' => 50,
                'collections' => array_filter([$colMen?->id]),
                'tagline' => 'Smoky Birch, Tart Pineapple, Blackcurrant & Majestic Oakmoss',
                'description' => 'A commanding powerhouse for the modern leader. Crisp Italian bergamot, juicy blackcurrant, and smoked birch wood create a magnetic masculine signature with beast-mode longevity and projection.',
                'top_notes_summary' => 'Pineapple, Blackcurrant, Bergamot, Crisp Apple',
                'heart_notes_summary' => 'Smoked Birch, Moroccan Jasmine, Rose, Patchouli',
                'base_notes_summary' => 'Grey Ambergris, Oakmoss, Musk, Bourbon Vanilla',
                'thumbnail_image' => 'assets/images/perfumes/smoked_birch.svg',
                'hover_image' => 'assets/images/perfumes/smoked_birch.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Gucci Bloom',
                'impression_of' => 'Bloom Floral Nectar (Gucci Bloom Impression)',
                'slug' => 'gucci-bloom-women',
                'sku' => 'PC-GCB-BLOOM',
                'category_id' => $catFloral ? $catFloral->id : 4,
                'fragrance_family_id' => $ffFloral ? $ffFloral->id : 2,
                'gender' => 'Women',
                'price' => 3500.00,
                'sale_price' => 2999.00,
                'compare_at_price' => 4200.00,
                'stock' => 35,
                'volume_ml' => 50,
                'collections' => array_filter([$colWomen?->id]),
                'tagline' => 'Natural White Floral Tuberose, Jasmine Sambac & Powdery Rangoon Creeper',
                'description' => 'Transport yourself to an expansive garden bursting with diverse blooms. Crafted with natural tuberose absolute and Jasmine Sambac extract, enriched by the rare powdery nuance of red Rangoon creeper.',
                'top_notes_summary' => 'Green Notes, Wild Orange Blossom',
                'heart_notes_summary' => 'Natural Tuberose, Jasmine Sambac, Rangoon Creeper',
                'base_notes_summary' => 'Orris Butter, Sandalwood, Royal Vanilla Musk',
                'thumbnail_image' => 'assets/images/perfumes/midnight_peony.svg',
                'hover_image' => 'assets/images/perfumes/midnight_peony.svg',
                'is_featured' => false,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => '9PM Night Out',
                'impression_of' => 'Night Out Exclusive (Afnan 9PM Night Edition Impression)',
                'slug' => '9pm-night-out-exclusive',
                'sku' => 'PC-9PM-NIGHTOUT',
                'category_id' => $catExclusive ? $catExclusive->id : 2,
                'fragrance_family_id' => $ffGourmand ? $ffGourmand->id : 5,
                'gender' => 'Men',
                'price' => 3850.00,
                'sale_price' => 3400.00,
                'compare_at_price' => 4500.00,
                'stock' => 45,
                'volume_ml' => 50,
                'collections' => array_filter([$colExclusive?->id, $colMen?->id]),
                'tagline' => 'Spiced Cinnamon Bark, Crisp Green Apple, Night Blossom & Deep Amber',
                'description' => 'The ultimate party and evening powerhouse. Blends mouth-watering crisp green apple and sweet cinnamon bark with magnetic dark amber and tonka bean, leaving an unforgettable trail in every room.',
                'top_notes_summary' => 'Spiced Cinnamon, Green Apple, Wild Bergamot',
                'heart_notes_summary' => 'Night Blooming Lavender, Orange Blossom, Lily of Valley',
                'base_notes_summary' => 'Golden Ambergris, Madagascar Vanilla, Tonka Bean, Patchouli',
                'thumbnail_image' => 'assets/images/perfumes/lahore_nights.svg',
                'hover_image' => 'assets/images/perfumes/lahore_nights_box.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => true,
            ],
            [
                'name' => 'Rebel',
                'impression_of' => 'Rebel Pour Homme Extrait',
                'slug' => 'rebel-men',
                'sku' => 'PC-RBL-MEN',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffFresh ? $ffFresh->id : 4,
                'gender' => 'Men',
                'price' => 3500.00,
                'sale_price' => 2999.00,
                'compare_at_price' => 4200.00,
                'stock' => 30,
                'volume_ml' => 50,
                'collections' => array_filter([$colMen?->id]),
                'tagline' => 'Electric Pink Pepper, Sparkling Citrus, Elemi Resin & Dark Cedar',
                'description' => 'Bold, daring, and unapologetically masculine. Rebel blends fiery spices with crisp Mediterranean citrus and smoky cedarwood resin to create an electric aura of confidence.',
                'top_notes_summary' => 'Pink Peppercorn, Italian Mandarin, Cardamom',
                'heart_notes_summary' => 'Elemi Resin, Clary Sage, Lavender',
                'base_notes_summary' => 'Smoked Cedarwood, Haitian Vetiver, Amber Crystals',
                'thumbnail_image' => 'assets/images/perfumes/vetiver_imperiale.svg',
                'hover_image' => 'assets/images/perfumes/vetiver_imperiale.svg',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new_arrival' => true,
            ],
            [
                'name' => '9PM (After 9)',
                'impression_of' => 'After 9 Pour Homme (JPG Ultra Male / 9PM Impression)',
                'slug' => '9pm-after-9',
                'sku' => 'PC-9PM-AFTER9',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffGourmand ? $ffGourmand->id : 5,
                'gender' => 'Men',
                'price' => 3600.00,
                'sale_price' => 3100.00,
                'compare_at_price' => 4400.00,
                'stock' => 50,
                'volume_ml' => 50,
                'collections' => array_filter([$colMen?->id]),
                'tagline' => 'Sweet Vanilla Mint, Spiced Cinnamon, Juicy Pear & Ambergris',
                'description' => 'The celebrated signature for nightlife and intimate evenings. A seductive fusion of succulent spiced pear, sweet vanilla mint, and warm tonka bean engineered for long-lasting sillage.',
                'top_notes_summary' => 'Juicy Pear, Wild Lavender, Mint, Bergamot',
                'heart_notes_summary' => 'Spiced Cinnamon, Clary Sage, Cumin',
                'base_notes_summary' => 'Black Bourbon Vanilla, Ambergris, Cedarwood, Patchouli',
                'thumbnail_image' => 'assets/images/perfumes/gourmand_tonka.svg',
                'hover_image' => 'assets/images/perfumes/gourmand_tonka.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Ombre Leather (The Leather)',
                'impression_of' => 'The Leather (Tom Ford Ombré Leather Impression)',
                'slug' => 'ombre-leather-the-leather',
                'sku' => 'PC-OML-THELEATHER',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffLeather ? $ffLeather->id : 3,
                'gender' => 'Men',
                'price' => 3950.00,
                'sale_price' => 3499.00,
                'compare_at_price' => 4800.00,
                'stock' => 40,
                'volume_ml' => 50,
                'collections' => array_filter([$colMen?->id]),
                'tagline' => 'Cardamom Noir, Rich Black Suede Leather, Jasmine & Earthy Moss',
                'description' => 'A tactile and boundless leather impression. Driven by textured black leather and spiced cardamom, softened by wild jasmine sambac and rich white moss for an intoxicating presence.',
                'top_notes_summary' => 'Cardamom Noir, Saffron',
                'heart_notes_summary' => 'Black Suede Leather, Jasmine Sambac',
                'base_notes_summary' => 'White Moss, Dark Patchouli, Amber',
                'thumbnail_image' => 'assets/images/perfumes/sultan_cuir.svg',
                'hover_image' => 'assets/images/perfumes/sultan_cuir_box.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Tuscan Leather (Leather Temptation)',
                'impression_of' => 'Leather Temptation (Tom Ford Tuscan Leather Impression)',
                'slug' => 'tuscan-leather-leather-temptation',
                'sku' => 'PC-TUS-LEATHER',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffLeather ? $ffLeather->id : 3,
                'gender' => 'Men',
                'price' => 3950.00,
                'sale_price' => 3499.00,
                'compare_at_price' => 4800.00,
                'stock' => 35,
                'volume_ml' => 50,
                'collections' => array_filter([$colMen?->id]),
                'tagline' => 'Wild Raspberry, Crimson Saffron, Night Thyme & Raw Tuscan Leather',
                'description' => 'The raw, sophisticated standard of luxury leather perfumery. Saffron and succulent raspberry lend a sweet modern contrast to prime Tuscan leather, frankincense, and smoked woods.',
                'top_notes_summary' => 'Wild Raspberry, Crimson Saffron, Wild Thyme',
                'heart_notes_summary' => 'Olibanum Frankincense, Night Jasmine',
                'base_notes_summary' => 'Tuscan Leather, Black Suede, Amberwood',
                'thumbnail_image' => 'assets/images/perfumes/sultan_cuir.svg',
                'hover_image' => 'assets/images/perfumes/sultan_cuir_box.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Sentinal',
                'impression_of' => 'Sentinal Private Reserve Exclusive',
                'slug' => 'sentinal-exclusive',
                'sku' => 'PC-SNT-EXCLUSIVE',
                'category_id' => $catExclusive ? $catExclusive->id : 1,
                'fragrance_family_id' => $ffWoody ? $ffWoody->id : 1,
                'gender' => 'Men',
                'price' => 4200.00,
                'sale_price' => 3700.00,
                'compare_at_price' => 5000.00,
                'stock' => 30,
                'volume_ml' => 50,
                'collections' => array_filter([$colExclusive?->id, $colMen?->id]),
                'tagline' => 'Dark Plum, Smoked Birch, Black Cardamom & Royal Ambergris',
                'description' => 'A private reserve extrait engineered for sovereign gravitas. Rich spiced plum blends seamlessly with aged cedarwood, smoky incense, and dark ambergris for an authoritative sillage.',
                'top_notes_summary' => 'Dark Spiced Plum, Cardamom, Bergamot',
                'heart_notes_summary' => 'Smoked Birch, Nutmeg, Cashmere Wood',
                'base_notes_summary' => 'Royal Ambergris, Aged Agarwood, Dark Vanilla',
                'thumbnail_image' => 'assets/images/perfumes/atlas_cedarwood.svg',
                'hover_image' => 'assets/images/perfumes/atlas_cedarwood.svg',
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new_arrival' => true,
            ],
            [
                'name' => 'Black Opium (Charm)',
                'impression_of' => 'Charm (YSL Black Opium Impression)',
                'slug' => 'black-opium-charm-women',
                'sku' => 'PC-BOP-CHARM',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffGourmand ? $ffGourmand->id : 5,
                'gender' => 'Women',
                'price' => 3500.00,
                'sale_price' => 2999.00,
                'compare_at_price' => 4200.00,
                'stock' => 45,
                'volume_ml' => 50,
                'collections' => array_filter([$colWomen?->id]),
                'tagline' => 'Shot of Dark Roasted Coffee, Orange Blossom, Pink Pepper & Sweet Vanilla',
                'description' => 'An addictive shot of adrenaline and sensual warmth. Opens with energizing dark espresso beans and spicy pink pepper, mellowing into velvety white flowers and rich bourbon vanilla.',
                'top_notes_summary' => 'Dark Roasted Coffee, Pink Pepper, Orange Blossom',
                'heart_notes_summary' => 'Jasmine Sambac, Bitter Almond, Licorice',
                'base_notes_summary' => 'Bourbon Vanilla, Patchouli, Cedarwood, Cashmere',
                'thumbnail_image' => 'assets/images/perfumes/velvet_orchid.svg',
                'hover_image' => 'assets/images/perfumes/velvet_orchid.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Crush',
                'impression_of' => 'Crush Velvet Extrait',
                'slug' => 'crush-unisex',
                'sku' => 'PC-CRS-UNISEX',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffFloral ? $ffFloral->id : 2,
                'gender' => 'Unisex',
                'price' => 3400.00,
                'sale_price' => 2899.00,
                'compare_at_price' => 4000.00,
                'stock' => 35,
                'volume_ml' => 50,
                'collections' => array_filter([$colUnisex?->id]),
                'tagline' => 'Wild Crushed Berries, Sunlit Peach Nectar & Golden Amber Crystals',
                'description' => 'A playful yet opulent cocktail of crushed summer fruits and golden amber warmth. Radiates irresistible charm and vibrant youthful charisma on both men and women.',
                'top_notes_summary' => 'Wild Crushed Berries, Peach Nectar, Pink Grapefruit',
                'heart_notes_summary' => 'Red Rose Petals, Peony, Magnolia Blossom',
                'base_notes_summary' => 'Amber Crystals, Soft Cashmere, White Musk',
                'thumbnail_image' => 'assets/images/perfumes/midnight_peony.svg',
                'hover_image' => 'assets/images/perfumes/midnight_peony.svg',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new_arrival' => true,
            ],
            [
                'name' => 'Republic (Stronger With You)',
                'impression_of' => 'Republic (Armani Stronger With You Impression)',
                'slug' => 'republic-stronger-with-you',
                'sku' => 'PC-REP-SWY',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffGourmand ? $ffGourmand->id : 5,
                'gender' => 'Unisex',
                'price' => 3600.00,
                'sale_price' => 3100.00,
                'compare_at_price' => 4400.00,
                'stock' => 40,
                'volume_ml' => 50,
                'collections' => array_filter([$colUnisex?->id, $colMen?->id]),
                'tagline' => 'Spiced Cardamom, Roasted Chestnut, Pink Pepper & Smoked Vanilla',
                'description' => 'An unpredictable and confident gourmand-fougere impression. Combines spicy pink pepper and cardamom with a delicious heart of candied chestnut and rich smoked bourbon vanilla.',
                'top_notes_summary' => 'Cardamom, Pink Pepper, Violet Leaves, Mint',
                'heart_notes_summary' => 'Candied Chestnut, Sage, Cinnamon, Melon',
                'base_notes_summary' => 'Bourbon Vanilla, Amberwood, Cedarwood, Guaiac Wood',
                'thumbnail_image' => 'assets/images/perfumes/cardamom_noir.svg',
                'hover_image' => 'assets/images/perfumes/cardamom_noir.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Bombshell',
                'impression_of' => 'Bombshell Flora Extrait (Victoria\'s Secret Bombshell Impression)',
                'slug' => 'bombshell-women',
                'sku' => 'PC-BMS-WOMEN',
                'category_id' => $catFloral ? $catFloral->id : 4,
                'fragrance_family_id' => $ffFloral ? $ffFloral->id : 2,
                'gender' => 'Women',
                'price' => 3400.00,
                'sale_price' => 2899.00,
                'compare_at_price' => 4000.00,
                'stock' => 50,
                'volume_ml' => 50,
                'collections' => array_filter([$colWomen?->id]),
                'tagline' => 'Purple Passion Fruit, Shangri-La Peony, Vanilla Orchid & Sunlit Citrus',
                'description' => 'Pakistan\'s most requested fruity-floral fragrance impression. Sparkling with exotic purple passionfruit and citrus sunshine, blended seamlessly with delicate Shangri-La peonies and vanilla orchids.',
                'top_notes_summary' => 'Purple Passion Fruit, Grapefruit, Pineapple, Strawberry',
                'heart_notes_summary' => 'Shangri-La Yellow Peony, Vanilla Orchid, Jasmine, Lily of the Valley',
                'base_notes_summary' => 'White Musk, Blonde Woods, Oakmoss',
                'thumbnail_image' => 'assets/images/perfumes/taif_rose_1888.svg',
                'hover_image' => 'assets/images/perfumes/taif_rose_1888.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Xerjoff Naxos (Caribbean Exclusive)',
                'impression_of' => 'Caribbean Exclusive (Xerjoff 1861 Naxos Impression)',
                'slug' => 'xerjoff-naxos-caribbean-exclusive',
                'sku' => 'PC-XRF-NAXOS',
                'category_id' => $catExclusive ? $catExclusive->id : 2,
                'fragrance_family_id' => $ffWoody ? $ffWoody->id : 1,
                'gender' => 'Unisex',
                'price' => 4500.00,
                'sale_price' => 3950.00,
                'compare_at_price' => 5500.00,
                'stock' => 30,
                'volume_ml' => 50,
                'collections' => array_filter([$colExclusive?->id, $colUnisex?->id, $colMen?->id]),
                'tagline' => 'Golden Mountain Honey, Sweet Blonde Tobacco, Sicilian Citrus & Tonka',
                'description' => 'A masterwork tribute to Sicilian heritage and Caribbean warmth. Opens with crisp Italian bergamot and lavender, melting into golden honey, sweet cinnamon, rich blonde tobacco leaves, and bourbon vanilla.',
                'top_notes_summary' => 'Bergamot, Sicilian Lemon, French Alpine Lavender',
                'heart_notes_summary' => 'Mountain Honey, Cinnamon Bark, Cashmeran, Jasmine Sambac',
                'base_notes_summary' => 'Blonde Tobacco Leaf, Tonka Bean, Madagascar Vanilla',
                'thumbnail_image' => 'assets/images/perfumes/grasse_collab.svg',
                'hover_image' => 'assets/images/perfumes/grasse_collab.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => true,
            ],
            [
                'name' => 'Azzaro Wanted (Mission)',
                'impression_of' => 'Mission (Azzaro Wanted / Most Wanted Impression)',
                'slug' => 'azzaro-wanted-mission',
                'sku' => 'PC-AZZ-WANTED',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffFresh ? $ffFresh->id : 4,
                'gender' => 'Men',
                'price' => 3600.00,
                'sale_price' => 3100.00,
                'compare_at_price' => 4400.00,
                'stock' => 40,
                'volume_ml' => 50,
                'collections' => array_filter([$colMen?->id]),
                'tagline' => 'Zesty Lemon, Warm Ginger, Cardamom & Smoky Amberwood',
                'description' => 'Designed for the charismatic achiever who lives life on his own terms. Fresh ginger and zesty lemon fuse with fiery Guatemalan cardamom and amberwood for an electrifying woody-spicy trail.',
                'top_notes_summary' => 'Calabrian Lemon, Spiced Ginger, Lavender, Mint',
                'heart_notes_summary' => 'Guatemalan Cardamom, Juniper, Apple, Geranium',
                'base_notes_summary' => 'Haitian Vetiver, Tonka Bean, Amberwood, Cedar',
                'thumbnail_image' => 'assets/images/perfumes/spiced_tea.svg',
                'hover_image' => 'assets/images/perfumes/spiced_tea.svg',
                'is_featured' => false,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'The White Oud',
                'impression_of' => 'The White Oud Soft Amber & Agarwood',
                'slug' => 'the-white-oud-unisex',
                'sku' => 'PC-WHO-UNISEX',
                'category_id' => $catOud ? $catOud->id : 1,
                'fragrance_family_id' => $ffWoody ? $ffWoody->id : 1,
                'gender' => 'Unisex',
                'price' => 3800.00,
                'sale_price' => 3300.00,
                'compare_at_price' => 4600.00,
                'stock' => 35,
                'volume_ml' => 50,
                'collections' => array_filter([$colUnisex?->id, $colExclusive?->id]),
                'tagline' => 'White Floral Dew, Spiced Cardamom, Soft White Agarwood & Skin Musk',
                'description' => 'A clean, ethereal take on traditional oud. White Oud blends transparent floral dew with cardamom spice and gentle white agarwood, creating a royal scent that is never overpowering.',
                'top_notes_summary' => 'White Floral Dew, Cardamom, Artemisia',
                'heart_notes_summary' => 'White Agarwood Resin, Ambergris, Jasmine',
                'base_notes_summary' => 'Clean Royal Musk, Mysore Sandalwood, Cypriol',
                'thumbnail_image' => 'assets/images/perfumes/white_royal_musk.svg',
                'hover_image' => 'assets/images/perfumes/white_royal_musk.svg',
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new_arrival' => true,
            ],
            [
                'name' => 'Arabian Sea (Bleu de Chanel)',
                'impression_of' => 'Bleu de Chanel Aquatic Marine (Arabian Sea Impression)',
                'slug' => 'arabian-sea-bleu-de-chanel-unisex',
                'sku' => 'PC-ARS-BDC',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffFresh ? $ffFresh->id : 4,
                'gender' => 'Unisex',
                'price' => 3800.00,
                'sale_price' => 3300.00,
                'compare_at_price' => 4600.00,
                'stock' => 50,
                'volume_ml' => 50,
                'collections' => array_filter([$colUnisex?->id, $colMen?->id]),
                'tagline' => 'Grapefruit, Marine Sea Salt, Smoked Incense & Rich Cedarwood',
                'description' => 'The ultimate expression of fresh oceanic sophistication. Opens with sun-drenched grapefruit and crisp mint, deepened by mysterious frankincense and rich sandalwood.',
                'top_notes_summary' => 'Grapefruit, Lemon, Mint, Pink Peppercorn',
                'heart_notes_summary' => 'Ginger, Nutmeg, Jasmine, Iso E Super',
                'base_notes_summary' => 'Incense, Vetiver, Cedarwood, Sandalwood, Patchouli',
                'thumbnail_image' => 'assets/images/perfumes/marine_amber.svg',
                'hover_image' => 'assets/images/perfumes/marine_amber.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Erba Pura (Roman Memory)',
                'impression_of' => 'Roman Memory (Sospiro / Xerjoff Erba Pura Impression)',
                'slug' => 'erba-pura-roman-memory-unisex',
                'sku' => 'PC-EBP-ROMAN',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffFresh ? $ffFresh->id : 4,
                'gender' => 'Unisex',
                'price' => 3950.00,
                'sale_price' => 3450.00,
                'compare_at_price' => 4800.00,
                'stock' => 45,
                'volume_ml' => 50,
                'collections' => array_filter([$colUnisex?->id]),
                'tagline' => 'Sicilian Orange, Calabrian Bergamot, Exotic Fruits & Sensual White Musk',
                'description' => 'A mouthwatering basket of glistening Mediterranean fruits soaked in sweet Sicilian citrus. Macerated with an aristocratic white musk and amber base that projects for days.',
                'top_notes_summary' => 'Sicilian Orange, Calabrian Bergamot, Sicilian Lemon',
                'heart_notes_summary' => 'Mediterranean Summer Fruits Basket',
                'base_notes_summary' => 'Sensual White Musk, Madagascar Bourbon Vanilla, Amber',
                'thumbnail_image' => 'assets/images/perfumes/murree_mist.svg',
                'hover_image' => 'assets/images/perfumes/murree_mist_box.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => false,
            ],
            [
                'name' => 'Hawas Ice (Ice Heaven)',
                'impression_of' => 'Ice Heaven (Rasasi Hawas Ice Impression)',
                'slug' => 'hawas-ice-ice-heaven-unisex',
                'sku' => 'PC-HWI-ICEHEAVEN',
                'category_id' => $catFrench ? $catFrench->id : 2,
                'fragrance_family_id' => $ffFresh ? $ffFresh->id : 4,
                'gender' => 'Unisex',
                'price' => 3950.00,
                'sale_price' => 3450.00,
                'compare_at_price' => 4800.00,
                'stock' => 50,
                'volume_ml' => 50,
                'collections' => array_filter([$colUnisex?->id, $colMen?->id]),
                'tagline' => 'Frozen Green Apple, Star Anise, Aquatic Driftwood, Plum & Ambergris',
                'description' => 'The colder, crisper edition of the viral Hawas formula. Sub-zero frozen Italian citrus and icy green apple meet aquatic mint and rich ambergris for maximum summer compliment factor.',
                'top_notes_summary' => 'Frozen Apple, Italian Bergamot, Sicilian Lemon, Star Anise',
                'heart_notes_summary' => 'Cardamom, Plum, Orange Blossom, Aquatic Accord',
                'base_notes_summary' => 'Ambergris, Musk, Driftwood, Oakmoss',
                'thumbnail_image' => 'assets/images/perfumes/murree_mist.svg',
                'hover_image' => 'assets/images/perfumes/murree_mist_box.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => true,
            ],
            [
                'name' => 'Silk Musk',
                'impression_of' => 'Silk Musk Royal Reserve Exclusive',
                'slug' => 'silk-musk-exclusive',
                'sku' => 'PC-SLK-MUSK',
                'category_id' => $catExclusive ? $catExclusive->id : 3,
                'fragrance_family_id' => $ffFloral ? $ffFloral->id : 2,
                'gender' => 'Unisex',
                'price' => 3950.00,
                'sale_price' => 3450.00,
                'compare_at_price' => 4800.00,
                'stock' => 35,
                'volume_ml' => 50,
                'collections' => array_filter([$colExclusive?->id, $colUnisex?->id]),
                'tagline' => 'Velvety White Lily, Silken Cashmere, Royal Skin Musk & Golden Honey',
                'description' => 'Pure luxury in liquid form. Silk Musk wraps the wearer in an angelic veil of soft white petals, sheer cashmere wood, and velvety royal musk that lingers intimately all day.',
                'top_notes_summary' => 'White Lily, Silk Petal Accord, Sweet Mandarin',
                'heart_notes_summary' => 'Powdery Cashmere, Jasmine Blossom, Golden Honey',
                'base_notes_summary' => 'Pure Royal White Musk, Amber Resin, Mysore Sandalwood',
                'thumbnail_image' => 'assets/images/perfumes/silk_bourbon.svg',
                'hover_image' => 'assets/images/perfumes/silk_bourbon.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => true,
            ],
            [
                'name' => '91 Sports',
                'impression_of' => '91 Sports Performance Extrait Exclusive',
                'slug' => '91-sports-exclusive',
                'sku' => 'PC-91-SPORTS',
                'category_id' => $catExclusive ? $catExclusive->id : 2,
                'fragrance_family_id' => $ffFresh ? $ffFresh->id : 4,
                'gender' => 'Men',
                'price' => 3850.00,
                'sale_price' => 3350.00,
                'compare_at_price' => 4600.00,
                'stock' => 40,
                'volume_ml' => 50,
                'collections' => array_filter([$colExclusive?->id, $colMen?->id]),
                'tagline' => 'Frosted Spearmint, Sea Salt Mist, Clary Sage & Smoked Cedarwood',
                'description' => 'Formulated for dynamic athletes and active lifestyles. Delivers an immediate blast of frosty spearmint and marine freshness supported by clean musk that thrives under body heat.',
                'top_notes_summary' => 'Frosted Spearmint, Italian Mandarin, Sea Salt',
                'heart_notes_summary' => 'Clary Sage, Lavender, Crisp Rosemary',
                'base_notes_summary' => 'Smoked Cedarwood, White Ambergris, Clean Musk',
                'thumbnail_image' => 'assets/images/perfumes/marine_amber.svg',
                'hover_image' => 'assets/images/perfumes/marine_amber.svg',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new_arrival' => true,
            ],
            [
                'name' => '91 Degree',
                'impression_of' => '91 Degree High Octane Extrait Exclusive',
                'slug' => '91-degree-exclusive',
                'sku' => 'PC-91-DEGREE',
                'category_id' => $catExclusive ? $catExclusive->id : 2,
                'fragrance_family_id' => $ffLeather ? $ffLeather->id : 3,
                'gender' => 'Men',
                'price' => 3850.00,
                'sale_price' => 3350.00,
                'compare_at_price' => 4600.00,
                'stock' => 40,
                'volume_ml' => 50,
                'collections' => array_filter([$colExclusive?->id, $colMen?->id]),
                'tagline' => 'Fiery Red Chili Pepper, Spiced Nutmeg, Saddle Leather & Dark Amber',
                'description' => 'High octane warmth that turns up the heat. A spicy leather powerhouse blending red pepper heat with crushed nutmeg, resinous labdanum, and rich dark amber.',
                'top_notes_summary' => 'Red Pepper, Pink Peppercorn, Calabrian Bergamot',
                'heart_notes_summary' => 'Nutmeg, Saddle Leather, Clove, Cinnamon',
                'base_notes_summary' => 'Dark Amber, Indonesian Patchouli, Smoked Vetiver',
                'thumbnail_image' => 'assets/images/perfumes/cardamom_noir.svg',
                'hover_image' => 'assets/images/perfumes/cardamom_noir.svg',
                'is_featured' => false,
                'is_bestseller' => false,
                'is_new_arrival' => true,
            ],
            [
                'name' => '91 Gold Edition',
                'impression_of' => '91 Gold Edition All Exclusive Reserve',
                'slug' => '91-gold-edition-exclusive',
                'sku' => 'PC-91-GOLD',
                'category_id' => $catExclusive ? $catExclusive->id : 1,
                'fragrance_family_id' => $ffWoody ? $ffWoody->id : 1,
                'gender' => 'Unisex',
                'price' => 4500.00,
                'sale_price' => 3950.00,
                'compare_at_price' => 5500.00,
                'stock' => 30,
                'volume_ml' => 50,
                'collections' => array_filter([$colExclusive?->id, $colUnisex?->id, $colMen?->id]),
                'tagline' => '24K Saffron, Rare Aged Agarwood, Bourbon Vanilla & Royal Ambergris',
                'description' => 'The crown jewel of the 91 collection. Hand-macerated with ultra-pure saffron strands, aged Cambodian agarwood, and opulent ambergris for unmatched regal distinction.',
                'top_notes_summary' => '24K Kashmiri Saffron, Cardamom Noir, Blood Orange',
                'heart_notes_summary' => 'Royal Damascus Rose, Golden Labdanum, Smoked Birch',
                'base_notes_summary' => 'Aged Cambodian Oud, Bourbon Vanilla, Golden Ambergris',
                'thumbnail_image' => 'assets/images/perfumes/oud_royale.svg',
                'hover_image' => 'assets/images/perfumes/oud_royale_box.svg',
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new_arrival' => true,
            ],
        ];

        // 6. Insert or update products
        $count = 0;
        foreach ($perfumes as $pData) {
            $collections = $pData['collections'] ?? [];
            unset($pData['collections']);

            $product = Product::where('slug', $pData['slug'])->orWhere('sku', $pData['sku'])->first();

            $payload = array_merge([
                'brand_id' => $brand->id,
                'concentration' => 'Extrait de Parfum (35% Oil Concentration)',
                'longevity' => '12-16 Hours (Long Lasting)',
                'sillage' => 'Strong / Noticeable Sillage',
                'season' => 'All Seasons',
                'time_of_day' => 'Day & Evening',
                'in_stock' => true,
                'is_active' => true,
                'rating_avg' => rand(48, 50) / 10,
                'reviews_count' => rand(15, 65),
                'meta_title' => $pData['name'] . ' | Perfumes Collection Pakistan',
                'meta_description' => $pData['tagline'] . '. High concentration luxury impression crafted in Pakistan.',
            ], $pData);

            if (!$product) {
                $product = Product::create($payload);
                $count++;
            } else {
                $product->update($payload);
            }

            // Attach collections
            if (!empty($collections)) {
                $product->collections()->syncWithoutDetaching($collections);
            }

            // Create 50ml and 100ml variants
            // 50ml Variant
            ProductVariant::firstOrCreate(
                [
                    'product_id' => $product->id,
                    'volume_ml' => 50,
                ],
                [
                    'size_label' => '50ml Flacon',
                    'price' => $product->price,
                    'sale_price' => $product->sale_price,
                    'sku' => $product->sku . '-50ML',
                    'stock' => $product->stock,
                    'is_default' => true,
                ]
            );

            // 100ml Variant
            $price100 = round($product->price * 1.65, -2);
            $salePrice100 = $product->sale_price ? round($product->sale_price * 1.65, -2) : null;

            ProductVariant::firstOrCreate(
                [
                    'product_id' => $product->id,
                    'volume_ml' => 100,
                ],
                [
                    'size_label' => '100ml Flacon',
                    'price' => $price100,
                    'sale_price' => $salePrice100,
                    'sku' => $product->sku . '-100ML',
                    'stock' => max(15, (int)($product->stock * 0.7)),
                    'is_default' => false,
                ]
            );
        }

        ActivityLog::record(
            'inventory_seeded',
            "Seeded {$count} new high-demand perfume inventory items from catalog image list with categories and collections."
        );
    }
}
